### ISSUE TITLE
SGIP 发送短信，没有特殊的情况报错，什么原因

### ISSUE THREAD

**Issue by BadDeveloper2022** [Lihuanghe/CMPPGate#22]
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at com.zx.sms.codec.sgip12.codec.SgipMessageCodecAggregator.write(SgipMessageCodecAggregator.java:50)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at com.zx.sms.handler.MessageLogHandler.write(MessageLogHandler.java:49)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.handler.traffic.ChannelTrafficShapingHandler.submitWrite(ChannelTrafficShapingHandler.java:186)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.write(AbstractTrafficShapingHandler.java:565)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at com.zx.sms.session.AbstractSessionStateManager.safewrite(AbstractSessionStateManager.java:534)
	at com.zx.sms.session.AbstractSessionStateManager.writeWithWindow(AbstractSessionStateManager.java:311)
	at com.zx.sms.session.AbstractSessionStateManager.write(AbstractSessionStateManager.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at com.zx.sms.handler.sgip.ReWriteNodeIdHandler.write(ReWriteNodeIdHandler.java:22)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1127)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1174)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1098)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at java.lang.Thread.run(Thread.java:662)

**Comment by BadDeveloper2022** [comment]
final EndpointManager manager = EndpointManager.INS;


        SgipClientEndpointEntity child = new SgipClientEndpointEntity();
        child.setHost("192.168.0.1");
        child.setPort(8801);
        child.setValid(true);
        //使用ssl加密数据流
        child.setUseSSL(false);
        child.setId("sgipchild");
        child.setLoginName("111");
        child.setLoginPassowrd("222");
        child.setValid(true);
        child.setChannelType(EndpointEntity.ChannelType.DUPLEX);
        child.setMaxChannels((short) 3);
        child.setRetryWaitTimeSec((short) 30);
        child.setMaxRetryCnt((short) 1);
        child.setReSendFailMsg(false);
        child.setIdleTimeSec((short) 30);

        child.setSupportLongmsg(EndpointEntity.SupportLongMessage.NONE);  //接收长短信时不自动合并
        manager.addEndpointEntity(child);
        manager.openEndpoint(child);
        //
        Thread.sleep(2000);
        manager.startConnectionCheckTask();
        Thread.sleep(2000);
        System.out.println("start.....");
        SgipSubmitRequestMessage message = new SgipSubmitRequestMessage();
       // message.setMsgContent(new SmsTextMessage("尊敬的用户欢迎使用！", SmsAlphabet.ASCII, SmsMsgClass.CLASS_0));
       // message.setMsgContent(new SmsTextMessage("尊敬的用户欢迎使用！", SmsAlphabet.ASCII, SmsMsgClass.CLASS_1));
        message.setMsgContent("尊敬的用户欢迎使用！");
        message.setExpiretime(null);
        message.setCorpid("11101");
        message.setChargenumber("000000000000000000000");
        message.setUsernumber("86" + "xxxx" + "");
        message.setFeetype((short)1);
        message.setSpnumber("10010");
        message.setFeevalue("0");
        message.setGivenvalue("0");
        message.setMorelatetomtflag((short) 2);
        message.setPriority((short) 0);
        message.setAgentflag((short) 1);
        message.setReportflag((short) 2);
        ChannelFuture obj = ChannelUtil.asyncWriteToEntity(child.getId(), message);
        System.out.println("exit....." + obj.isDone());
        System.out.println("exit....." + obj.sync());
        Thread.sleep(5000);
        System.out.println("exit2....." + obj.isDone());
        EndpointManager.INS.close();

**Comment by Lihuanghe** [comment]
child.setSupportLongmsg(EndpointEntity.SupportLongMessage.NONE);
不拆分长短信时，发送时要自己拆分。参考ChannelUtil.syncwrite的拆分方法来发送

**Comment by BadDeveloper2022** [comment]
JDK 1.6  好像不是这个问题，我换成双向的也是一样错误

**Comment by BadDeveloper2022** [comment]
child.setSupportLongmsg(EndpointEntity.SupportLongMessage.BOTH);

**Comment by BadDeveloper2022** [comment]
SessionState.Connect.....
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at com.zx.sms.codec.sgip12.codec.SgipMessageCodecAggregator.write(SgipMessageCodecAggregator.java:50)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at com.zx.sms.handler.MessageLogHandler.write(MessageLogHandler.java:49)

**Comment by BadDeveloper2022** [comment]
已连接，但是短信内容打包的时候 出错

**Comment by Lihuanghe** [comment]
message.setExpiretime(null); 
不用的字段不要设置为null ，保持默认即可

**Comment by BadDeveloper2022** [comment]
是时间设置Null的问题

**Comment by BadDeveloper2022** [comment]
io.netty.util.concurrent.BlockingOperationException: DefaultPromise@5d391d(incomplete)
	at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:395)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:225)
	at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:337)
	at com.holly.test.SessionConnectedHandler.userEventTriggered(SessionConnectedHandler.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)

**Comment by BadDeveloper2022** [comment]
现在客户端收到的内容为空，NULL
我各种编码都试了，我们以前的是编码code-15 GBK的

**Comment by BadDeveloper2022** [comment]
可以了，bytes来解决了，非常感谢，
还有一个小问题，闪信能不能不让保存
