### ISSUE TITLE
received the same index

### ISSUE THREAD

**Issue by wangmb** [Lihuanghe/CMPPGate#34]
@Lihuanghe 你好，4连接数压测的时候出现如下问题，是什么原因导致的呢？

`com.zx.sms.common.NotSupportedException: received the same index
	at com.zx.sms.codec.cmpp.wap.FrameHolder.merge(FrameHolder.java:103) ~[sms-core-2.1.12.1.jar:na]
	at com.zx.sms.codec.cmpp.wap.LongMessageFrameHolder.mergeFrameHolder(LongMessageFrameHolder.java:252) ~[sms-core-2.1.12.1.jar:na]
	at com.zx.sms.codec.cmpp.wap.LongMessageFrameHolder.putAndget(LongMessageFrameHolder.java:197) ~[sms-core-2.1.12.1.jar:na]
	at com.zx.sms.codec.cmpp.wap.AbstractLongMessageHandler.decode(AbstractLongMessageHandler.java:33) [sms-core-2.1.12.1.jar:na]
	at com.zx.sms.codec.cmpp.wap.AbstractLongMessageHandler.decode(AbstractLongMessageHandler.java:1) [sms-core-2.1.12.1.jar:na]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) [netty-codec-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) [netty-codec-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-codec-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.52.Final.jar:4.1.52.Final]`

**Comment by Lihuanghe** [comment]
长短信合并的时候，收到了相同编号的片断。
