### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by Programmer-ZX** [Lihuanghe/CMPPGate#8]
打包后，没有包含resource下.properties和.xml文件
`Caused by: java.lang.NullPointerException
	at com.zx.sms.config.PropertiesUtils.loadProperties(PropertiesUtils.java:66)
	at com.zx.sms.config.PropertiesUtils.<clinit>(PropertiesUtils.java:10)
	... 26 more
![qq 20171106091242](https://user-images.githubusercontent.com/23043552/32975340-5a0255b6-cc41-11e7-9b5a-a932434617df.png)
`

**Comment by Lihuanghe** [comment]
我在eclipse里debug的时候，偶而也会遇到这个NPE，然后Project->clean一下就好了。
用mvn package打包从未遇到此错误
